$(function(){
  //story-about-us
  $('.main-contents-img1').hover(
    function(){
      $(this).css('display','none');
      $('.main-contents-img-hover1').css('display','block');
      $('.main-contents-img-shadow1').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.main-contents-img-shadow1').css('display','none');
      $('.main-contents-img-hover1').css('display','none');
    }
  );
  $('.main-contents-img2').hover(
    function(){
      $(this).css('display','none');
      $('.main-contents-img-hover2').css('display','block');
      $('.main-contents-img-shadow2').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.main-contents-img-shadow2').css('display','none');
      $('.main-contents-img-hover2').css('display','none');
    }
  );
  $('.main-contents-img3').hover(
    function(){
      $(this).css('display','none');
      $('.main-contents-img-hover3').css('display','block');
      $('.main-contents-img-shadow3').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.main-contents-img-shadow3').css('display','none');
      $('.main-contents-img-hover3').css('display','none');
    }
  );
  // some-of-our-work
  $('.some-of-our-work-img1').hover(
    function(){
      $(this).css('display','none');
      $('.some-of-our-work-img-hover1').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.some-of-our-work-img-hover1').css('display','none');
    }
  );
  $('.some-of-our-work-img2').hover(
    function(){
      $(this).css('display','none');
      $('.some-of-our-work-img-hover2').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.some-of-our-work-img-hover2').css('display','none');
    }
  );
  $('.some-of-our-work-img3').hover(
    function(){
      $(this).css('display','none');
      $('.some-of-our-work-img-hover3').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.some-of-our-work-img-hover3').css('display','none');
    }
  );
  $('.some-of-our-work-img4').hover(
    function(){
      $(this).css('display','none');
      $('.some-of-our-work-img-hover4').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.some-of-our-work-img-hover4').css('display','none');
    }
  );
  $('.some-of-our-work-img5').hover(
    function(){
      $(this).css('display','none');
      $('.some-of-our-work-img-hover5').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.some-of-our-work-img-hover5').css('display','none');
    }
  );
  $('.some-of-our-work-img6').hover(
    function(){
      $(this).css('display','none');
      $('.some-of-our-work-img-hover6').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.some-of-our-work-img-hover6').css('display','none');
    }
  );
  $('.some-of-our-work-img7').hover(
    function(){
      $(this).css('display','none');
      $('.some-of-our-work-img-hover7').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.some-of-our-work-img-hover7').css('display','none');
    }
  );
  // what-we-do-title-area
  $('.what-we-do-title-area1').hover(
    function(){
      $('.what-we-do-text1').css('display','block');
    },function(){
      $('.what-we-do-text1').css('display','none');
    }
  );
  $('.what-we-do-title-area2').hover(
    function(){
      $('.what-we-do-text2').css('display','block');
    },function(){
      $('.what-we-do-text2').css('display','none');
    }
  );
  $('.what-we-do-title-area3').hover(
    function(){
      $('.what-we-do-text3').css('display','block');
    },function(){
      $('.what-we-do-text3').css('display','none');
    }
  );

  //people
  $('.js-people-img1').hover(
    function(){
      $(this).css('display','none');
      $('.people-shadow1').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.people-shadow1').css('display','none');
    }
  ); 
  $('.js-people-img2').hover(
    function(){
      $(this).css('display','none');
      $('.people-shadow2').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.people-shadow2').css('display','none');
    }
  ); 
  $('.js-people-img3').hover(
    function(){
      $(this).css('display','none');
      $('.people-shadow3').css('display','block');
    },function(){
      $(this).css('display','block');
      $('.people-shadow3').css('display','none');
    }
  ); 
});
